Chat Test Cases & Minor Bug Fix
CSC207-2022F-UofT/course-project-zuck-s-children pull request #132
Opened 2022-12-08 22:19 UTC by SiruLee

- Testing on sending a message, opening a chatroom, and accessing chat data
- Minor bug fix in sending a notification when a message is sent

2022-12-08 22:22 UTC, tankenji approved these changes

2022-12-08 22:30 UTC, nina-huangg approved these changes
Great work Jiheon!

I saw changes in the Notification UI in response to chat click, looks amazing. Good documentation as well.

2022-12-08 23:07 UTC, XiWang16 approved these changes
Great test cases for the chat feature! For the tests for the components in the ui package, do you think we can merge those into our tests for ui classes to increase simplicity?

2022-12-08 23:13 UTC, nina-huangg submitted a review, later dismissed

2022-12-08 23:14 UTC, karenrni approved these changes

2022-12-08 23:44 UTC, lancenigel approved these changes

2022-12-09 01:08 UTC, SanzSS requested changes
please move chatUI into the chat package.

2022-12-09 02:01 UTC, lancenigel submitted a review, later dismissed

2022-12-09 02:09 UTC, tankenji submitted a review, later dismissed

2022-12-09 02:13 UTC, XiWang16 submitted a review, later dismissed

2022-12-09 02:23 UTC, closed without merging